/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CarsImport } from './routes/cars'
import { Route as BrandsImport } from './routes/brands'
import { Route as CarsNewImport } from './routes/cars_.new'
import { Route as CarsCarSlugImport } from './routes/cars_.$carSlug'
import { Route as BrandsNewImport } from './routes/brands_.new'
import { Route as BrandsBrandSlugImport } from './routes/brands_.$brandSlug'
import { Route as CarsCarSlugGenerationsNewImport } from './routes/cars_.$carSlug_.generations_.new'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const CarsRoute = CarsImport.update({
  path: '/cars',
  getParentRoute: () => rootRoute,
} as any)

const BrandsRoute = BrandsImport.update({
  path: '/brands',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const CarsNewRoute = CarsNewImport.update({
  path: '/cars/new',
  getParentRoute: () => rootRoute,
} as any)

const CarsCarSlugRoute = CarsCarSlugImport.update({
  path: '/cars/$carSlug',
  getParentRoute: () => rootRoute,
} as any)

const BrandsNewRoute = BrandsNewImport.update({
  path: '/brands/new',
  getParentRoute: () => rootRoute,
} as any)

const BrandsBrandSlugRoute = BrandsBrandSlugImport.update({
  path: '/brands/$brandSlug',
  getParentRoute: () => rootRoute,
} as any)

const CarsCarSlugGenerationsNewRoute = CarsCarSlugGenerationsNewImport.update({
  path: '/cars/$carSlug/generations/new',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/brands': {
      preLoaderRoute: typeof BrandsImport
      parentRoute: typeof rootRoute
    }
    '/cars': {
      preLoaderRoute: typeof CarsImport
      parentRoute: typeof rootRoute
    }
    '/brands/$brandSlug': {
      preLoaderRoute: typeof BrandsBrandSlugImport
      parentRoute: typeof rootRoute
    }
    '/brands/new': {
      preLoaderRoute: typeof BrandsNewImport
      parentRoute: typeof rootRoute
    }
    '/cars/$carSlug': {
      preLoaderRoute: typeof CarsCarSlugImport
      parentRoute: typeof rootRoute
    }
    '/cars/new': {
      preLoaderRoute: typeof CarsNewImport
      parentRoute: typeof rootRoute
    }
    '/cars/$carSlug/generations/new': {
      preLoaderRoute: typeof CarsCarSlugGenerationsNewImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  BrandsRoute,
  CarsRoute,
  BrandsBrandSlugRoute,
  BrandsNewRoute,
  CarsCarSlugRoute,
  CarsNewRoute,
  CarsCarSlugGenerationsNewRoute,
])

/* prettier-ignore-end */
