import { Country } from "@prisma/client";

export const carBrandsToImport: {
  id: string;
  name: string;
  slug: string;
  website: string;
  country: Country;
  logoUrl: string;
}[] = [
  {
    id: "8272a395-0819-4d22-a502-75d3469e288c",
    name: "Volvo",
    slug: "volvo",
    country: Country.SWEDEN,
    website: "https://www.volvocars.com/",
    logoUrl: "/brands/volvo.png",
  },
  {
    id: "6f849336-3646-4d91-83b5-ec7348c13462",
    name: "Volkswagen",
    slug: "volkswagen",
    country: Country.GERMANY,
    website: "https://www.volkswagen.se/",
    logoUrl: "/brands/volkswagen.png",
  },
  {
    id: "107c6cc2-374b-43b5-b00a-937206246df0",
    name: "BMW",
    slug: "bmw",
    country: Country.GERMANY,
    website: "https://www.bmw.se/",
    logoUrl: "/brands/bmw.png",
  },
  {
    id: "c9290011-c8e1-4bee-bb16-ce980bc8ebe8",
    name: "Audi",
    slug: "audi",
    country: Country.GERMANY,
    website: "https://www.audi.se/",
    logoUrl: "/brands/audi.png",
  },
  {
    id: "156e6717-a557-46d0-9e59-1bd65f439d02",
    name: "Mercedes-Benz",
    slug: "mercedes-benz",
    country: Country.GERMANY,
    website: "https://www.mercedes-benz.se/",
    logoUrl: "/brands/mercedes-benz.png",
  },
  {
    id: "b80e4171-c20a-4d3c-b4e7-202e72b41468",
    name: "Toyota",
    slug: "toyota",
    country: Country.JAPAN,
    website: "https://www.toyota.se/",
    logoUrl: "/brands/toyota.png",
  },
  {
    id: "81bba14c-8a76-478c-8a00-67e5333b6cad",
    name: "Ford",
    slug: "ford",
    country: Country.UNITED_STATES,
    website: "https://www.ford.se/",
    logoUrl: "/brands/ford.png",
  },
  {
    id: "e5bccd4d-c5d4-4590-a594-b8f171a1dc0e",
    name: "Peugeot",
    slug: "peugeot",
    country: Country.FRANCE,
    website: "https://www.peugeot.se/",
    logoUrl: "/brands/peugeot.png",
  },
  {
    id: "a75a2dd2-fa75-4aa1-9649-39327efc8c50",
    name: "Renault",
    slug: "renault",
    country: Country.FRANCE,
    website: "https://www.renault.se/",
    logoUrl: "/brands/renault.png",
  },
  {
    id: "00e4f1e2-6ee6-43b5-a3aa-ee8e0954a245",
    name: "Skoda",
    slug: "skoda",
    country: Country.CZECH_REPUBLIC,
    website: "https://www.skoda.se/",
    logoUrl: "/brands/skoda.png",
  },
  {
    id: "efb769d4-bb05-45e5-9cb7-7a8ad290343c",
    name: "Kia",
    slug: "kia",
    country: Country.SOUTH_KOREA,
    website: "https://www.kia.com/se/",
    logoUrl: "/brands/kia.png",
  },
  {
    id: "3dff05df-97ee-438a-a93a-588d2baffa93",
    name: "Hyundai",
    slug: "hyundai",
    country: Country.SOUTH_KOREA,
    website: "https://www.hyundai.se/",
    logoUrl: "/brands/hyundai.png",
  },
  {
    id: "3c6d20e2-f299-43c5-8c35-505a3aba0623",
    name: "Mazda",
    slug: "mazda",
    country: Country.JAPAN,
    website: "https://www.mazda.se/",
    logoUrl: "/brands/mazda.png",
  },
  {
    id: "4da047c1-3c78-46cf-9df7-d31bf480d788",
    name: "Nissan",
    slug: "nissan",
    country: Country.JAPAN,
    website: "https://www.nissan.se/",
    logoUrl: "/brands/nissan.png",
  },
  {
    id: "6c347aaf-3442-4490-b11a-5e9ad7920956",
    name: "Citroën",
    slug: "citroen",
    country: Country.FRANCE,
    website: "https://www.citroen.se/",
    logoUrl: "/brands/citroen.png",
  },
  {
    id: "1233f207-8eed-45c0-850c-080c302382a9",
    name: "Opel",
    slug: "opel",
    country: Country.GERMANY,
    website: "https://www.opel.se/",
    logoUrl: "/brands/opel.png",
  },
  {
    id: "df359ffc-3ba3-4063-bc33-8020258186af",
    name: "Seat",
    slug: "seat",
    country: Country.SPAIN,
    website: "https://www.seat.se/",
    logoUrl: "/brands/seat.png",
  },
  {
    id: "f55c9faa-6540-44c6-a59f-22053349ff73",
    name: "Suzuki",
    slug: "suzuki",
    country: Country.JAPAN,
    website: "https://www.suzuki.se/",
    logoUrl: "/brands/suzuki.png",
  },
  {
    id: "98992a8d-3dd7-4802-a0f5-1b37729401fb",
    name: "Mitsubishi",
    slug: "mitsubishi",
    country: Country.JAPAN,
    website: "https://www.mitsubishi-motors.se/",
    logoUrl: "/brands/mitsubishi.png",
  },
  {
    id: "23f998ea-97b3-4a3d-b88e-db51fdf95354",
    name: "Honda",
    slug: "honda",
    country: Country.JAPAN,
    website: "https://www.honda.se/",
    logoUrl: "/brands/honda.png",
  },
  {
    id: "03dcf3e8-1553-44ef-83dc-5b1652b14374",
    name: "Subaru",
    slug: "subaru",
    country: Country.JAPAN,
    website: "https://www.subaru.se/",
    logoUrl: "/brands/subaru.png",
  },
  {
    id: "f2e9a6e7-6a68-4e0a-a157-535769f669d5",
    name: "Dacia",
    slug: "dacia",
    country: Country.ROMANIA,
    website: "https://www.dacia.se/",
    logoUrl: "/brands/dacia.png",
  },
  {
    id: "08aca749-3210-4c25-bcda-9468f8030583",
    name: "Fiat",
    slug: "fiat",
    country: Country.ITALY,
    website: "https://www.fiat.se/",
    logoUrl: "/brands/fiat.png",
  },
  {
    id: "e8a17dcf-2435-4e4b-85ae-507661a5a331",
    name: "Alfa Romeo",
    slug: "alfa-romeo",
    country: Country.ITALY,
    website: "https://www.alfaromeo.se/",
    logoUrl: "/brands/alfa-romeo.png",
  },
  {
    id: "c0989e2e-eb5e-4a3e-9a74-494babb31619",
    name: "Jeep",
    slug: "jeep",
    country: Country.UNITED_STATES,
    website: "https://www.jeep.se/",
    logoUrl: "/brands/jeep.png",
  },
  {
    id: "a305c36c-b3dd-402d-a237-d8ceb16f167b",
    name: "Land Rover",
    slug: "land-rover",
    country: Country.UNITED_KINGDOM,
    website: "https://www.landrover.se/",
    logoUrl: "/brands/land-rover.png",
  },
  {
    id: "7fe0b2ce-e0af-4bab-ab2e-b33365ebe8d7",
    name: "Jaguar",
    slug: "jaguar",
    country: Country.UNITED_KINGDOM,
    website: "https://www.jaguar.se/",
    logoUrl: "/brands/jaguar.png",
  },
];
